@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class company {
   userid: integer
   name: varchar(32)
   industry: varchar(32)
   banned: boolean
   contactdetails: varchar(64)
   companyid: integer
}
class job {
   companyid: integer
   title: varchar(100)
   description: varchar(1024)
   salary: varchar(32)
   location: varchar(64)
   jobid: integer
}
class reports {
   companyid: integer
   report: varchar(256)
}
class skill {
   skill: varchar(32)
   skillid: integer
}
class student {
   userid: integer
   firstname: varchar(32)
   studymajor: varchar(32)
   university: varchar(32)
   matrikelnumber: varchar(32)
   lastname: varchar(32)
   studentid: integer
}
class node2 as "student_has_skill  /* table between student and skill */" {
   studentid: integer
   skillid: integer
}
class node4 as "student_has_topic  /* table between student and topic */" {
   studentid: integer
   topicid: integer
}
class topic {
   topic: varchar(32)
   topicid: integer
}
class user {
   username: varchar(32)
   password: varchar(100)
   email: varchar(32)
   role: varchar(32)
   userid: integer
}

company  -[#595959,plain]-^  user    : "userid"
job      -[#595959,plain]-^  company : "companyid"
reports  -[#595959,plain]-^  company : "companyid"
student  -[#595959,plain]-^  user    : "userid"
node2    -[#595959,plain]-^  skill   : "skillid"
node2    -[#595959,plain]-^  student : "studentid"
node4    -[#595959,plain]-^  student : "studentid"
node4    -[#595959,plain]-^  topic   : "topicid"
@enduml
